## 00. Pytorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

if you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
!nvidia-smi

Thu Sep 14 19:48:05 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 537.13                 Driver Version: 537.13       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2060      WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   52C    P8               5W /  80W |    343MiB /  6144MiB |     10%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## Introdaction to Tensors

### Creating Tensors

PyTorch tensors are creating using 'torch.tensor()' = https://pytorch.org/docs/stable/tensors.html

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrics
matrics = torch.tensor([[7,8],[9,10]])
matrics

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrics.ndim

2

In [11]:
matrics[1]

tensor([ 9, 10])

In [12]:
matrics.shape

torch.Size([2, 2])

In [13]:
# Tensor
tensor = torch.tensor([[[1,2,3],[3,4,6],[56,7,8]]])
tensor

tensor([[[ 1,  2,  3],
         [ 3,  4,  6],
         [56,  7,  8]]])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([1, 3, 3])

### Random tensors

Why are random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adujust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Troch random tensors = https://pytorch.org/docs/stable/generated/torch.randint.html

In [16]:
#  Create a random tensor of size (3, 4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4050, 0.4932, 0.7829, 0.3310],
        [0.6223, 0.7700, 0.3613, 0.6841],
        [0.0954, 0.1514, 0.8499, 0.0139]])

In [17]:
# Create a random tensor with similar shape to an tensor
random_image_tensor = torch.rand(size=(224,224,3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [18]:
torch.rand(3,3)

tensor([[0.9650, 0.2140, 0.4235],
        [0.6257, 0.5844, 0.1826],
        [0.5171, 0.6389, 0.6549]])

### Zeros and Ones

In [19]:
#  Creating a tensor of all zeros
zeros  = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# Create tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype, random_tensor.dtype

(torch.float32, torch.float32)

### Creating a range of tensors and tensors-like

In [22]:
# Use torch.range() and get deprecated message,use torch.arange()
one_to_ten = torch.arange(1,10, step=1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# Creating tensor-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note** Tensor datatypes is one of the 3 big errors you'll run int with PyTorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [24]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,# more about dtype: https://pytorch.org/docs/stable/tensors.html
                               device=None, # What device is zour tensor on
                               requires_grad=False) # whether or to track gradients with this tensors operations
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [27]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [28]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor atribute)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from tensor, can use `tensor.device`


In [29]:
# Create a tensor
some_tensor = torch.rand(3,4)

In [30]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Size of tensor: {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9501, 0.8656, 0.3036, 0.2818],
        [0.6332, 0.9078, 0.0919, 0.9769],
        [0.8831, 0.5848, 0.6519, 0.6196]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Size of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensors operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [31]:
# Creating a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [32]:
# Multiply tensors by 10
tensor * 10

tensor([10, 20, 30])

In [33]:
#  Substract 10
tensor - 10

tensor([-9, -8, -7])

In [34]:
# Try out Pytorch in- build functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [35]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrics multiplications

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More about it: https://www.mathsisfun.com/algebra/matrix-multiplying.html

Try how it works: http://matrixmultiplication.xyz

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimentions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [36]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [37]:
# Matrics multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [38]:
tensor

tensor([1, 2, 3])

In [39]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [40]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 2 ms


In [41]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### One of the most common errors in deep learning: shape errors

In [42]:
#  Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm == torch.matmul # ERROR

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [43]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [44]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Remember for first rule!!!
### Check second link for more understanding 	↑

# Finding the min, max, mean, sum etc (tensor aggregation)

In [45]:
# Creating a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [46]:
# Finding the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [47]:
# Finding max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [48]:
# Finding mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() # no int

(tensor(45.), tensor(45.))

In [49]:
# Finding sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [50]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [51]:
#  Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [52]:
x[0]

tensor(0)

In [53]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [54]:
x[9]

tensor(90)

## Reshaping, staking, squeezing and unsqueezing tensor

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Staking - combine multiple tensors on top of each other (vstak) or side by side (hstak)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [55]:
#  Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [56]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [57]:
#  Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [58]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [59]:
# Stack tensor on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [60]:
# Squeeze
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimentions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [61]:
# Unsqueeze
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimention with unsqueeze
x_unsqueez = x_reshaped.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueez}")
print(f"New shape: {x_unsqueez.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]])
New shape: torch.Size([1, 9, 1])


In [62]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [63]:
print("Let's change value at index (0,0,0)")
x_original[0,0,0] = 30300303
x_original[0,0,0], x_permuted[0,0,0]

Let's change value at index (0,0,0)


(tensor(30300304.), tensor(30300304.))

## Indexing (selecting data from tensors)

Indexing in PyTorch is similar to indexing with NumPy

In [64]:
#  Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [65]:
#  Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [66]:
# Let's inde on the midle bracket (dim=1)
x[0, 0]

tensor([1, 2, 3])

In [67]:
# Let's index on the most inner bracket (last dimention)
x[0,0,0]

tensor(1)

In [68]:
#  You can also use ":" to select "all" of a target dimention
x[:,0]

tensor([[1, 2, 3]])

In [69]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimention
x[:,:,1]

tensor([[2, 5, 8]])

In [70]:
# Get all values of the 0 dimention but only the 1 index value of 1st and 2nd dimention
x[:,1,1]

tensor([5])

In [71]:
#  Get index 0 of 0th and 1st dimention and all values of 2nd dimention
x[0,0,:]

tensor([1, 2, 3])

In [72]:
# Index on x to return 9
print(x[:,2,2], x[0,2,2])
# Index on x to return 3, 6, 9
print(x[:,:,2])

tensor([9]) tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensor & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [73]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: whn converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [74]:
# Change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [75]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [76]:
#  Change the tensor, what happens to 'numpy_tensor'?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "favour" the randomness.

In [77]:
import torch

# Create two tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_B == random_tensor_A)

tensor([[0.1860, 0.0111, 0.8626, 0.0277],
        [0.3195, 0.5270, 0.3071, 0.4905],
        [0.4414, 0.5319, 0.5697, 0.1898]])
tensor([[0.9674, 0.7636, 0.4167, 0.4224],
        [0.2750, 0.7262, 0.7000, 0.4497],
        [0.9620, 0.7469, 0.0263, 0.1632]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [78]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)
# torch.manual_seed(RANDOM_SEED) # seed works only ones the next will be fully random
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPUs (and making faster computations)
GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use zour own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options... see this post for what option to get: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, AZure, these services allow zou to rent computers on the cloud and access them.

For 2, 3 Pytorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [79]:
!nvidia-smi

Thu Sep 14 19:48:18 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 537.13                 Driver Version: 537.13       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2060      WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   52C    P8               7W /  80W |    313MiB /  6144MiB |     14%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [80]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if avai;able, else default to CPU

In [81]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [82]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [83]:
# Creating a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [84]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [87]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [86]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)

## Exercises & Extra-curriculum

See exercises for this notebook here: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

In [88]:
#  2
import torch
x = torch.rand(7,7)
x, x.shape

(tensor([[0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062, 0.9516],
         [0.0753, 0.8860, 0.5832, 0.3376, 0.8090, 0.5779, 0.9040],
         [0.5547, 0.3423, 0.6343, 0.3644, 0.7104, 0.9464, 0.7890],
         [0.2814, 0.7886, 0.5895, 0.7539, 0.1952, 0.0050, 0.3068],
         [0.1165, 0.9103, 0.6440, 0.7071, 0.6581, 0.4913, 0.8913],
         [0.1447, 0.5315, 0.1587, 0.6542, 0.3278, 0.6532, 0.3958],
         [0.9147, 0.2036, 0.2018, 0.2018, 0.9497, 0.6666, 0.9811]]),
 torch.Size([7, 7]))

In [89]:
# 3
y = torch.rand(1,7)
z = x.matmul(y.T) # torch.matmul(x,y.T)
y, z, z.shape

(tensor([[0.0874, 0.0041, 0.1088, 0.1637, 0.7025, 0.6790, 0.9155]]),
 tensor([[1.3417],
         [1.9172],
         [2.0426],
         [0.6368],
         [1.8116],
         [1.1753],
         [2.1538]]),
 torch.Size([7, 1]))

In [90]:
# 4
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
x = torch.rand(7,7)
# torch.manual_seed(RANDOM_SEED)
y = torch.rand(1,7)
z = x.matmul(y.T)
x,y,z,z.shape

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]),
 tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [91]:
# 5
torch.cuda.manual_seed(1234)

In [92]:
# 6
device = "cuda" if torch.cuda.is_available() else "cpu"
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)
x = torch.rand(2,3).to(device)
# torch.manual_seed(RANDOM_SEED)
y = torch.rand(2,3).to(device)
device, x, y

('cuda',
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [93]:
# 7
z = torch.matmul(x,y.T)
z

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [94]:
# 8
z.max(), z.min()

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

In [95]:
# 9
z.argmin(), z.argmax()

(tensor(0, device='cuda:0'), tensor(3, device='cuda:0'))

In [96]:
# 10
torch.manual_seed(7)
x = torch.rand(1,1,1,10)
y = x.squeeze()
print(x,x.shape)
print(y,y.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
